version: '3'

services:
  order-postgresql:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - 25432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=very-secure-password
      - POSTGRESQL_POSTGRES_PASSWORD=very-secure-password
      - POSTGRESQL_DATABASE=order_db
      - POSTGRESQL_WAL_LEVEL=logical

  shopping-cart-postgresql:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - 35432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=very-secure-password
      - POSTGRESQL_POSTGRES_PASSWORD=very-secure-password
      - POSTGRESQL_DATABASE=shopping_cart_db
      - POSTGRESQL_WAL_LEVEL=logical

  zookeeper:
    image: quay.io/debezium/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka:
    image: quay.io/debezium/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      ZOOKEEPER_CONNECT: zookeeper:2181

  connect:
    image: quay.io/debezium/connect:latest
    ports:
      - 8083:8083
    depends_on:
      - kafka
      - order-postgresql
      - shopping-cart-postgresql
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_connect_statuses

  dbz-ui:
    image: quay.io/debezium/debezium-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - connect
    environment:
      - KAFKA_CONNECT_URIS=http://connect:8083
