version: '3.9'

services:
  order-postgresql:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - 25432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=very-secure-password
      - POSTGRESQL_POSTGRES_PASSWORD=very-secure-password
      - POSTGRESQL_DATABASE=order_db
      - POSTGRESQL_WAL_LEVEL=logical

  shopping-cart-postgresql:
    image: 'bitnami/postgresql:15.3.0'
    ports:
      - 35432:5432
    environment:
      - POSTGRESQL_USERNAME=user
      - POSTGRESQL_PASSWORD=very-secure-password
      - POSTGRESQL_POSTGRES_PASSWORD=very-secure-password
      - POSTGRESQL_DATABASE=shopping_cart_db
      - POSTGRESQL_WAL_LEVEL=logical

  zookeeper:
    image: quay.io/debezium/zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181

  kafka-server-1:
    image: quay.io/debezium/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
      - 9092:9092
      - 9101:9101
    environment:
      KAFKA_BROKER_ID: 1
      ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: EXTERNAL:PLAINTEXT,CLIENT:PLAINTEXT
      KAFKA_LISTENERS: EXTERNAL://localhost:29092,CLIENT://kafka-server-1:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: EXTERNAL
      KAFKA_ADVERTISED_LISTENERS: EXTERNAL://localhost:29092,CLIENT://kafka-server-1:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR_MIN_INSYNC_REPLICAS: 1
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost

  connect:
    image: quay.io/debezium/connect:latest
    ports:
      - 8083:8083
    depends_on:
      - order-postgresql
      - shopping-cart-postgresql
      - kafka-server-1
    environment:
      BOOTSTRAP_SERVERS: kafka-server-1:9092
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: my_connect_configs
      OFFSET_STORAGE_TOPIC: my_connect_offsets
      STATUS_STORAGE_TOPIC: my_connect_statuses
      KEY_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      ENABLE_DEBEZIUM_SCRIPTING: "true"

  dbz-ui:
    image: quay.io/debezium/debezium-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - connect
    environment:
      - KAFKA_CONNECT_URIS=http://connect:8083
